=== David8344/Atividade-5-POS/Q1/Carros.dtd
<!ELEMENT listaautomoveis (automovel*)>
<!ELEMENT automovel (descricao, caracteristicas, preco)>
<!ELEMENT descricao (#PCDATA)>
<!ATTLIST descricao combustivel CDATA #REQUIRED>
<!ELEMENT caracteristicas (cor, quilometragem, fotografia, obs)>
<!ELEMENT cor (#PCDATA)>
<!ATTLIST cor nome CDATA #REQUIRED>
<!ELEMENT quilometragem (#PCDATA)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT obs (#PCDATA)>

=== David8344/Atividade-5-POS/Q1/Carros.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE listaautomoveis SYSTEM "carros.dtd">

<listaautomoveis>
    <automovel>
        <descricao combustivel="GLP/>
         
        <caracteristicas>
            <cor nome="azul" />
            <quilometragem>100km</quilometragem>

            <fotografia />

            <obs>um pouco arranhado</obs>


        </caracteristicas>
        <preco>68000</preco>

    </automovel>
</listaautomoveis>
